-- Performance indexes for hotstock-be-v1
-- Generated by performance optimization review

-- Index for RefreshToken.userId (speeds up logout, token revocation)
CREATE INDEX IF NOT EXISTS "RefreshToken_userId_idx" ON "RefreshToken"("userId");
CREATE INDEX IF NOT EXISTS "RefreshToken_expiresAt_idx" ON "RefreshToken"("expiresAt");

-- Index for PortfolioStock.symbol (speeds up stock lookups by symbol)
CREATE INDEX IF NOT EXISTS "PortfolioStock_portfolioId_idx" ON "PortfolioStock"("portfolioId");
CREATE INDEX IF NOT EXISTS "PortfolioStock_symbol_idx" ON "PortfolioStock"("symbol");

-- Index for AuditLog (speeds up user audit queries, action filtering)
CREATE INDEX IF NOT EXISTS "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX IF NOT EXISTS "AuditLog_action_idx" ON "AuditLog"("action");
CREATE INDEX IF NOT EXISTS "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- Index for PortfolioSignal (speeds up signal lookups by symbol)
CREATE INDEX IF NOT EXISTS "PortfolioSignal_portfolioId_idx" ON "PortfolioSignal"("portfolioId");
CREATE INDEX IF NOT EXISTS "PortfolioSignal_symbol_idx" ON "PortfolioSignal"("symbol");
